### ISSUE TITLE
Apply v2.7.2 tag

### ISSUE THREAD

**Issue by smf8** [gubernator-io/gubernator#13]
Hi, Would you please kindly apply the tag `v.2.7.2` for docker image?

**Comment by thrawn01** [comment]
ha, I just noticed this issue! I just created a new release https://github.com/gubernator-io/gubernator/releases/tag/v2.7.2

**Comment by thrawn01** [comment]
Also, thank you for the fix. otel can be a pain sometimes and I appreciate it.
