### ISSUE TITLE
Peering authentication

### ISSUE THREAD

**Issue by japem** [gubernator-io/gubernator#2]
_I originally opened this [issue](https://github.com/mailgun/gubernator/issues/226) on the mailgun/gubernator repo and was told to move it here_

Is there any way to authenticate peering requests? As far as I can tell, there is to be no way to hook into the gRPC client created by the peering instance to add any sort of credentials to the peering request object, nor is there support for mTLS.

How is a use case that considers rate limit statuses to be sensitive supposed to make use of the peering feature?

**Comment by thrawn01** [comment]
@japem I'm now back from holiday, sorry for the wait.

You can specify TLS for the client Gubernator will use by setting these config options.
https://github.com/gubernator-io/gubernator/blob/master/example.conf#L117-L119

Authentication is preformed via TLS certificate authentication.

**Comment by thrawn01** [comment]
Closed due to age
