### ISSUE TITLE
v2.4.0 added breaking change now requiring a configuration file.

### ISSUE THREAD

**Issue by pbennett** [gubernator-io/gubernator#3]
This has always been defined as an optional file and environment overrides were fine.
Upgrading from 2.3.2 to 2.4 is hard failure in all of my deployments.

https://github.com/mailgun/gubernator/commit/452c5b5e102c740f2f404007a343f1811d713637#diff-906dccb3a093f9867818c8b4ded48155bae5a39d40f0c408869e8b0820b8e60dR79

**Comment by thrawn01** [comment]
@pbennett thank you for reporting this, I have a PR with a fix and added a test for this regression.
