### ISSUE TITLE
Getting a panic report: "panic: close of closed channel"

### ISSUE THREAD

**Issue by ihqtim** [gubernator-io/gubernator#35]
This is the line num "vendor/github.com/gubernator-io/gubernator/v2/peer_client.go:424"

Team has just started to investigate

**Comment by ihqtim** [comment]
Have reviewed the logic and the panic triggering channel is only closed in 1 place. Below is the function in peer_client.go that the panic originates from:
```
  // Shutdown waits until all outstanding requests have finished or the context is cancelled.
  // Then it closes the grpc connection.
  func (c *PeerClient) Shutdown(ctx context.Context) error {
	  // ensure we don't leak goroutines, even if the Shutdown times out
	  defer c.conn.Close()
  
	  waitChan := make(chan struct{})
	  go func() {
		  // drain in-flight requests
		  c.wgMutex.Lock()
		  defer c.wgMutex.Unlock()
		  c.wg.Wait()
  
		  // clear errors
		  c.lastErrs = collections.NewLRUCache(100)
  
		  // signal that no more items will be sent
		  c.queueClosed.Store(true)
		  close(c.queue) // <== this is line 424
  
		  close(waitChan)
	  }()
  
	  select {
	  case <-ctx.Done():
		  return ctx.Err()
	  case <-waitChan:
		  return nil
	  }
  }
```

`Shutdown(...)` is a public function. I have not traced all code paths that may call `Shutdown(...)`, however I believe the issue is that if, for some reason, something calls `Shutdown(...)` a second time the `close(c.queue)` runs a 2nd time, casing a panic that kills our servers.

Maybe, rather than calling `c.queueClosed.Store(true)` a CompareAndSwap could be used; if the atomic boolean is already true then skip calling `close(c.queue)`

**Comment by ihqtim** [comment]
Totally understand that this is an open source "use at your own risk" situation. This issue is killing our main server application process on random peers when we run upgrades; the problem is real. My guess is that we see this more frequently as we are now upgrading more frequently & have larger server cluster sizes.

@thrawn01 looking for your guidance here

**Comment by thrawn01** [comment]
Thank you for mentioning me on this issue, GH doesn't always notify me when new issues are created.

Are you using the gubernator server, or the library embedded into your application? When using things as a library often shutdown code can call close() or shutdown multiple times in odd ways... I've had this happen to me several times 😄 

Something I've been doing in newer projects is setting a `atomic.isShutdown` variable when `Close()` or `Shutdown()` is called. I think calling Shutdown() multiple times should be a forgivable sin, so protecting `Shutdown()` via `isShutdown` is probably the correct solution here.

Can you test https://github.com/gubernator-io/gubernator/pull/37 and report back?

**Comment by ihqtim** [comment]
Thanks for that; we will deploy to our QA cluster today and report back once we have had it run for a couple of days (applying this patch required us to upgrade some other dependencies, hence want to make sure nothing else has been impacted accidently)

**Comment by ihqtim** [comment]
Thanks for this @thrawn01; you may close this issue, we have not had it repeat since applying the fix.
